OPM/IFEM-Elasticity

SIMElasticity.h
Du trenger denne for å regne ut integralet av sigma*n over randa spesifisert via ny tag
<boundaryforce set="name"/> inne i <elasticity> scope.
=> Added: Method and input option for calculation of traction resultant

Linear/main_LinEl.C
To be merged with OPM/IFEM#112
=> Changed: Signature of SIMbase::initSystem

Linear/Test/triangular-neumann.reg, Linear/Test/triangular-neumann.xinp
=> Added: Regression test for Neumann problem with triangles

jenkins/build.sh
fsi couple us to navier-stokes and its dependencies
=> add all downstreams to jenkins build scripts

Beam/SIMElasticBar.C, Beam/SIMElasticBar.h, Linear/SIMLinElBeamC1.C, Linear/SIMLinElKL.C
Requires OPM/IFEM#141.
Kjell Magne want to model a beam with discontinous slopes, that is best represented by a 3-patch model. Then this became an issue.
=> Fixed: Handling of nodal loads in multi-patch models

Linear/AnalyticSolutions.C
Downstream of https://github.com/OPM/IFEM/pull/138
=> adjust to anasol changes

Beam/ElasticBar.h, Beam/ElasticBeam.h, Beam/ElasticCable.h, Elasticity.h, Linear/KirchhoffLovePlate.h, LinearElasticity.h, NewmarkDriver.h
This quells warnings with clang (and pgc).
=> add using statements to quell warnings

Beam/SIMElasticBar.h, Elasticity.C, Elasticity.h, Linear/AnalyticSolutions.h, Linear/KirchhoffLovePlate.C
Downstream changes due to OPM/IFEM#152
=> Added: Missing include statements due to recent upstream change

Linear/main_LinEl.C
Essentially, move the initAdaptor call to before registering fields in the data exporter.
See OPM/IFEM#159.
=> Downstream changes due to recent AdaptiveSIM cleaning

Linear/SIMLinElBeamC1.C, Linear/SIMLinElBeamC1.h, Linear/SIMLinElKL.C, Linear/SIMLinElKL.h, Linear/Test/Annulus2D.reg, Linear/Test/Annulus3D.reg, Linear/Test/AnnulusWithTemp2D.reg, Linear/Test/Hole2D-NURBS.reg, Linear/Test/LR/NavierIcrack_p2.reg, Linear/Test/MidShipFrame.reg, Linear/Test/NavierPart_p2.reg, Linear/Test/NavierPart_p3.reg, Linear/Test/NavierPoint_p3.reg, Linear/Test/NavierPress_p2.reg, Linear/Test/NavierPress_p3.reg, Linear/main_LinEl.C
Prelude to the residual error implementation.
=> Various updates for Kirchhoff-Love

Elasticity.C, Elasticity.h, Linear/KirchhoffLovePlate.C, Linear/KirchhoffLovePlate.h, Linear/Test/Annulus2D.reg, Linear/Test/Annulus3D.reg, Linear/main_LinEl.C
=> Fixed: External energy correction for problems with constraints

Elasticity.C, Elasticity.h, Linear/AnalyticSolutions.C, Linear/AnalyticSolutions.h, Linear/SIMLinElKL.C, Linear/main_LinEl.C
=> Anasol project

Linear/Test/LR/disc-stair-adap.reg
=> Regtest fix after it broke from IFEM PR #190

Linear/Test/Hole2D-immS1-p1.reg, Linear/Test/Hole2D-immS1-p1.xinp, Linear/Test/Hole2D-immS2-p1.reg, Linear/Test/Hole2D-immS2-p1.xinp
=> Added: Regression tests for immersed boundary with stabilization

Linear/Test/LR/disc-stair-adap.reg
To go along [IFEM PR#207](https://github.com/OPM/IFEM/pull/207)
=> Updated regression test with increased (LR) multipatch refinement footprint

Linear/CMakeLists.txt, Linear/Test/LR/disc-stair-adap.reg
also respect IFEM_SERIAL_TESTS_IN_PARALLEL to avoid running
these tests in parallel jenkins configuration
=> really fix disc-stair-adap after main library update

SIMElasticity.h
Is this what you had in mind @akva2 ?
Not tested yet.
=> Added: Generate threading groups for boundary force integration

Linear/main_LinEl.C
=> Added: Pre-parsing of input file to read dimension and adaptive parameters

Linear/Test/Cantilever-Cable3p.reg, Linear/Test/Cantilever-Cable3p.xinp
=> Changed: Regression test update due to recent fix in main library

Linear/SIMLinElBeamC1.C, Linear/SIMLinElBeamC1.h, Linear/main_LinEl.C, Shell/SIMKLShell.C, Shell/SIMKLShell.h
=> Adaptivity with point load and higher precision in norm/component output

Linear/KirchhoffLovePlate.C, Linear/SIMLinElKL.h, Linear/main_LinEl.C, NewmarkDriver.h, NonlinearDriver.C, NonlinearDriver.h, SIMElasticityWrap.h, Shell/CMakeLists.txt, Shell/KirchhoffLoveShell.C, Shell/KirchhoffLoveShell.h, Shell/Test/Cantilever-p3-restart.reg, Shell/main.C
Downstream of OPM/IFEM#282.
Also includes restart support for the nonlinear shell application.
Also includes the items from #56, except the memory leak commit which can't be done that way
=> Restart support

Elasticity.h, SIMElasticityWrap.h
To be used by PoroElasticity to compute time-step dependent scaling factor during initialization.
=> Added: virtual method init on integrand level

Beam/SIMElastic1D.C, Beam/SIMElastic1D.h, Beam/SIMElasticBar.C, Beam/SIMElasticBar.h, ElasticBase.C, ElasticBase.h, KirchhoffLove.C, KirchhoffLove.h, Linear/SIMLinElBeamC1.C, Linear/SIMLinElBeamC1.h, Linear/Test/PlateWithColumns_p2.reg, Linear/Test/PlateWithColumns_p2.xinp, Linear/Test/SSbeamPointLoad.reg, Linear/Test/SSbeamPointLoad.xinp, Linear/Test/SScablePointLoad.reg, Linear/Test/SScablePointLoad.xinp, Shell/NLKirchhoffLoveShell.C, Shell/SIMKLShell.C, Shell/SIMKLShell.h
Also support for multiple `<pressure>` tags
=> Point loads with arbitrary location in 1D

NewmarkDriver.h, NonlinearDriver.C, NonlinearDriver.h, Shell/main.C
Downstream of https://github.com/OPM/IFEM/pull/308
=> adjust for new restart code

Beam/SIMElasticBar.C, Linear/Test/PinchedHemisphere-p4.reg, Linear/Test/ScordelisLo-p4-4x4.hreg, Linear/Test/ScordelisLo-p4-4x4.reg, Linear/main_LinEl.C, Shell/KirchhoffLoveShell.C, Shell/SIMKLShell.C, Shell/SIMKLShell.h
Needed for doing adaptive shell analysis
=>  Fixed: Set nrcmp correctly for KirchhoffLoveShell

Linear/KirchhoffLovePlate.C, Linear/SIMLinElBeamC1.C, Linear/SIMLinElBeamC1.h, Linear/Test/SSbeamPointLoad-adap.reg, Linear/Test/SSbeamPointLoad-adap.xinp, Linear/Test/SSbeamPointLoad-graded.reg, Linear/Test/SSbeamPointLoad-graded.xinp
=> Added: Adaptive 1D example for regression testing

jenkins/build.sh
Downstream of https://github.com/OPM/IFEM/pull/333
=> changed: mark IFEM-Stokes and IFEM-NavierStokes as sidestreams

IsotropicTextureMat.C
Downstream of https://github.com/OPM/IFEM/pull/341
=> changed: use singleton wrapper for stb_image

Linear/main_LinEl.C
Request from the master students
=> Fixed: Dump displacements for final adapted grid

KirchhoffLove.h, Linear/SIMLinElKL.C, Linear/Test/LR/Cantilever-KLshell.reg, Linear/Test/LR/Cantilever-KLshell.xinp, Shell/SIMKLShell.C
=> Added: Use of ASMu2DC1 for Kirchhoff-Love and LR meshes

Elasticity.C, KirchhoffLove.C, LinearElasticity.C
=> Added: Argument partID in the writeVectors and writePoints methods

Linear/main_LinEl.C, NonlinearDriver.C
Added: Print of max point-wise stress values.
Fixed: Also dump sol-file after adaptive simulation.
=> Two small dump features

ElasticBase.C, ElasticBase.h, Elasticity.C, Elasticity.h, Linear/SIMLinEl.h, Linear/Test/CanTS2D-p1.reg, Linear/Test/CanTS2D-p1.xinp, Linear/Test/CanTS2D-p2.reg, Linear/Test/CanTS2D-p2.xinp, Linear/Test/CanTS2D-p3.reg, Linear/Test/CanTS2D-p3.xinp, Linear/Test/LR/CanTS2D-p1.reg, Linear/Test/LR/CanTS2D-p1.xinp, Linear/main_LinEl.C, LinearElasticity.C, LinearElasticity.h, NonlinearDriver.C, SIMElasticity.h
=>  Added: Variational Consistent Postprocessing of sectional forces

Linear/Test/triangular-neumann.reg
=> update regtest after upstream quadrature rule fix

Elasticity.C, Elasticity.h, Linear/Test/PipeJoint-NURBS.reg, Linear/main_LinEl.C, LinearElasticity.C
Feature request from Arcon Prosjekt AS,
Requires OPM/IFEM#377.
=> Added: Option to compute and print maximum stress values on patch level

ElasticBase.C, Elasticity.C, Elasticity.h, Linear/CMakeLists.txt, Linear/ModalDriver.C, Linear/ModalDriver.h, Linear/SIMLinElModal.h, Linear/Test/CanTS2D-p2-dmp.reg, Linear/Test/CanTS2D-p2-dmp.xinp, Linear/Test/CanTS2D-p2-dyn.reg, Linear/Test/CanTS2D-p2-dyn.xinp, Linear/Test/CanTS2D-p2-restart.reg, Linear/main_LinEl.C, LinearElasticity.C, LinearElasticity.h, NewmarkDriver.h, Shell/main.C
By no means finished, does not work yet...
Opening early such that others ( @akva2 ) can have a go on it.
Requires OPM/IFEM#379
=> Support for modal time integration of linear dynamics problems

Linear/Test/PolePinchedSphere-p3.reg
This one started failing on me.
=> Changed: PolePinchedSphere test more generous

LinIsotropic.C, LinIsotropic.h
...of these parameters as well, only for the completeness.
This replaces the first commit in #100 which now is obsolete after the merge of OPM/IFEM#395
=> Added: sub-tags <Poisson> and <density> for allowing spatial variation

Elasticity.C, KirchhoffLove.C, LinearElasticity.C, SIMElasticity.h
=> Changed: Remove argument partID again

Beam/BeamProperty.C, Beam/BeamProperty.h, Beam/ElasticBeam.C, Beam/ElasticBeam.h, Beam/SIMElasticBar.C, Beam/SIMElasticBar.h, Linear/SIMLinElBeamC1.C, Linear/Test/BeamFrame.reg, Linear/Test/BeamFrame.xinp, Linear/Test/NREL_5MW_blade-vibration.reg, Linear/Test/Utkrager.reg
Coordinate system issues, patchwise cross section properties, etc.
=> Various beam element fixes

Linear/SIMmcStatic.C, Linear/SIMmcStatic.h, Linear/main_LinEl.C
=> Added: HDF5 output for coupled multi-sim analysis

NewmarkDriver.h, NonlinearDriver.C, SIMElasticity.h, SIMElasticityWrap.h
with serialization of discretization bases as well as the external energy path integral
(otherwise the reported external energy is wrong after restart).
Requires OPM/IFEM#472.
=> Adaptive restart support

Linear/CMakeLists.txt, Linear/SIMLinEl.h, Linear/SIMLinElModal.h, Linear/SIMLinElSup.C, Linear/SIMLinElSup.h, Linear/Test/SSmembrane-p1.xinp, Linear/Test/SSsolid-p2.xinp, Linear/Test/TestStaticCondensation.C, Linear/main_LinEl.C
=> Added: Static condensation for linear elasticity problems

Linear/SIMLinEl.h, Linear/main_LinEl.C
Supposed to replace https://github.com/TheBB/IFEM-Elasticity/tree/bridgehack
Requires OPM/IFEM#484.
=> Added: Command-line options -ignoreSol and -RHSonly

Elasticity.C
buffer is too small to fit a full size_t
=> fixed: sprintf warning

Elasticity.h, SIMElasticity.h
=> Added: Missing include and forward declaration due to upstream change

ArcLengthDriver.C, Linear/SIMLinEl.h, Linear/Test/TestStaticCondensation.C
=> Changed: newLHS removed in solveSystem method

.gitignore, Linear/Test/Beam+KLcyl-p3.reg, Linear/Test/LR/CanTS2D-p1-VCPs.reg, Linear/Test/PolePinchedSphere-p3.reg, Shell/SIMKLShell.C
My new HP zBook with Ununtu 20.04 gave some smaller regression discrepancies
=> Minor round-off issues

Linear/SIMLinEl.h, Linear/Test/CanTS2D-p1.reg, Linear/Test/LR/CanTS2D-p1-VCPs.reg, Linear/Test/stretch-p1.reg, Linear/main_LinEl.C, SIMElasticity.h
=> Changed: Print reaction forces for each section, not only the first one

Elasticity.C, Elasticity.h, Linear/SIMLinEl.h, Linear/Test/CanTS2D-p2-dmp.reg, Linear/Test/CanTS2D-p2-dyn.reg, Linear/Test/CanTS2D-p2-qstat.reg, Linear/Test/PipeJoint-vibration.reg, SIMElasticity.h
=> Added: Calculation of interface force resultants from internal forces

Elasticity.C, Elasticity.h, ElasticityUtils.h, Linear/SIMLinEl.h, Linear/Test/CanTS2D-p1.reg, Linear/Test/CanTS2D-p2.reg, Linear/Test/LR/CanTS2D-p1-VCPs.reg, Linear/Test/MidShipFrame.vreg, Linear/Test/stretch-p1.reg, Linear/main_LinEl.C, LinearElasticity.C, LinearElasticity.h, NonlinearDriver.C, NonlinearDriver.h, SIMElasticity.C, SIMElasticity.h
such that it can be used for Nonlinear simulations also.
Requires OPM/IFEM#546
=> Generalization of interface force calculations

Beam/CMakeLists.txt, CMakeLists.txt, Linear/CMakeLists.txt, Shell/CMakeLists.txt
To quell warnings on ubuntu jammy.
=> changed: bump minimum cmake version

Linear/SIMLinEl.h, Linear/SIMLinElKL.C, Linear/SIMLinElSup.C, SIMElasticity.C, SIMElasticity.h, SIMElasticityWrap.h, Shell/SIMKLShell.C
And associated header clean-up.
=> make SIMElasticity a private template

Linear/main_LinEl.C
Added a non-stabilized version of the Hole test, and a new test for testing the `<levelset>` feature.
Downstream of OPM/IFEM#380.
=> More immersed boundary testing

Beam/ElasticBar.C, Beam/ElasticBeam.C, ElasticBase.C, ElasticBase.h, Elasticity.C, LinearElasticity.C
Downstream of OPM/IFEM#584. Labeling of element matrices and vectors for debug print.
=> Added: Element matrix/vector names for debug print

Linear/Test/LR/PointLoadedPlate-NURBS.reg, Linear/Test/LR/PointLoadedPlate-adap.xinp, Linear/Test/LR/ScordelisPoint-NURBS.reg
Downstream of https://github.com/OPM/IFEM/pull/585
=> update regression tests for LR nurbs changes

Beam/CMakeLists.txt, CMakeLists.txt, Linear/CMakeLists.txt, Shell/CMakeLists.txt
Same as https://github.com/OPM/IFEM/pull/618
=> bump minimum cmake version and move required tag before project

Elasticity.C, KirchhoffLove.C
Downstream of https://github.com/OPM/IFEM/pull/642
=> changed: functionality has been renamed timeDerivative

Linear/Test/Annulus3D.xinp, Linear/Test/Hole2D-immS1-p1.xinp, Linear/Test/Hole2D-immS2-p1.xinp, Linear/Test/LR/PointLoadedPlate+project.xinp, Linear/Test/LR/PointLoadedPlate-adap.xinp, Linear/Test/LR/exact_p2.xinp, Linear/Test/PlateLineLoad.xinp, Linear/Test/PlateWithColumns_p2.xinp, Linear/Test/PointLoadedPlate-project-file.xinp, Linear/Test/SquarePoint_p3.xinp, Linear/Test/exact_p1.xinp, Linear/Test/exact_p2.xinp
- invalid comments
- missing quotes
=> fixed: broken XML constructs

KirchhoffLove.C, KirchhoffLove.h, Linear/KirchhoffLovePlate.C, Linear/KirchhoffLovePlate.h, Linear/ModalDriver.h, Linear/SIMLinElBeamC1.C, Linear/SIMLinKLModal.C, Linear/SIMLinKLModal.h, Linear/Test/RectPlate-modal.reg, Linear/Test/RectPlate-modal.xinp, Linear/main_LinEl.C, Shell/KirchhoffLoveShell.C, Shell/KirchhoffLoveShell.h
But only tested for plate problems so far.
=> Added: Modal time integration for linear plate and shell problems

Linear/Test/Biharmonic1D-p3.reg, Linear/Test/CanTS2D-fields-p2.reg, Linear/Test/CanTS2D-p1.reg, Linear/Test/CanTS2D-p2.reg, Linear/Test/CanTS2D-p3.reg, Linear/Test/Harmonic1D-p3.reg, Linear/Test/Hole2D-immS1-p1.reg, Linear/Test/Hole2D-immS2-p1.reg, Linear/Test/LR/CanTS2D-p1-VCPs.reg, Linear/Test/LR/CanTS2D-p1.reg, Linear/Test/LR/exact_p2.reg, Linear/Test/SSbeamPointLoad-adap.reg, Linear/Test/SSbeamPointLoad-graded.reg, Linear/Test/SSbeamPointLoad-project-file.reg, Linear/Test/SSbeamPointLoad-project.reg, Linear/Test/exact_p1.reg, Linear/Test/exact_p2.reg
Downstream of https://github.com/OPM/IFEM/pull/667
=> adjust regression tests for anasol print

Linear/Test/Utkrager.vreg, NewmarkDriver.h
Downstream test for OPM/IFEM#684
=> Added: Regression test to VTF-output for beams

Elasticity.h, Linear/ModalSim.h, Linear/SIMLinEl.h, Linear/SIMLinElKL.C, Linear/SIMLinElKL.h, Linear/SIMLinElModal.h, Linear/SIMLinKLModal.C, Linear/SIMLinKLModal.h, Linear/main_LinEl.C
=> Modal simulation refactoring

KirchhoffLove.C, Linear/ModalDriver.C, Linear/ModalDriver.h, NewmarkDriver.h, NonlinearDriver.C
=> Added: Extraction of nodal velocity and acceleration

LinIsotropic.C, Linear/SIMLinElBeamC1.C, Linear/SIMLinElBeamC1.h, LinearElasticity.C, LinearElasticity.h, SIMElasticity.C
Harmless stuff, mostly due to missing delete of heap-allocated objects
=> Fix some memory leaks detected by valgrind

Beam/ElasticBar.C, Beam/ElasticBeam.C, ElasticBase.C, ElasticBase.h, Elasticity.C, Elasticity.h, Linear/ModalDriver.C, NewmarkDriver.h, SIMElasticityWrap.C
=> Allocate more primary solution vectors for dynamics simulation

Beam/ElasticBeam.C, Beam/ElasticBeam.h, Beam/SIMElasticBar.C, Linear/Test/BeamFrame.reg, Linear/Test/SPR/BeamFrame.reg, Linear/Test/SPR/boatbeam.reg, Linear/Test/Tripod.reg, Linear/Test/Utkrager-dyn.reg, Linear/Test/Utkrager.reg, Linear/Test/Utkrager.xinp, Linear/Test/boatbeam.reg, Linear/main_LinEl.C
The faulty corotational update is removed, to lessen confusion.
Will perhaps be revisted later.
=> Cleaned ElasticBeam integrand for linear/dynamics only

ElasticBase.C, ElasticBase.h, ElasticityArgs.C, ElasticityArgs.h, Linear/SIMLinElSup.C, Linear/SIMLinElSup.h, Linear/Test/Annulus3D.reg, Linear/Test/SPR/Annulus3D.reg, Linear/Test/SPR/WedgeStretch.reg, Linear/Test/WedgeStretch.reg, Linear/main_LinEl.C
=> Use new  class HasGravityBase, etc.

Linear/main_LinEl.C
Downstream of OPM/IFEM#790 (the second commit there).
=> Fixed: Initalize time-dependent dirichlet conditions for specified time

Beam/BeamProperty.C, Beam/BeamProperty.h, Linear/Test/Beam+Uprofil-p2.reg, Linear/Test/Beam+supel.reg, Linear/Test/SPR/Beam+Uprofil-p2.reg, Linear/Test/SPR/Beam+supel.reg
The new formula is obtained from the Nastran documentation.
=> Fixed: Torsion stiffness for rectangular cross section (Box)

Linear/CMakeLists.txt
Downstream of https://github.com/OPM/IFEM/pull/806
=> adjust to new ifem_add_test_app api

Shell/SIMKLShell.C
Downstream of https://github.com/OPM/IFEM/pull/814
=> prefix LR include paths with LR/

Linear/Test/TestStaticCondensation.C
Downstream of https://github.com/OPM/IFEM/pull/818
=> add support for catch2 v2

Linear/SIMLinElSup.C, Linear/SIMLinElSup.h
=> Changed: Let writeGlvS2() return updated idBlock value on success

NewmarkDriver.h
=> Changed: Velocity and Acceleration output now handled by parent class
