OPM/IFEM-Elasticity

- SIMElasticity.h
to avoid warning on undefined property during preprocessing. This removes the warning on undefined property sets during preprocessing.
Remember to pull the IFEM master before trying this one (the OTHER enum value, didn't bother a separate PR for that harmless one-liner). Could be a similar fix is needed for other apps (Stokes, etc,) using separate property codes for boundary force integration.
> Added: Set property type to OTHER for the boundary force code

- ElasticBase.C
- ElasticBase.h
- Elasticity.C
- SIMElasticity.C
- SIMElasticity.h
Then we are also able to set the initial value of its step member
from outside, using the setIntegrationPrm method.
> Changed: Dynamically allocate the BDFD2 member, and only when needed.

- Linear/CMakeLists.txt
In some apps, like FiniteDeformation and OpenFrac, it is used `\\` as continuation marker in the EXTRA_DOXY_PATH definition, whereas in others, like this one and BeamSIM, only a single `\` is used. Kjell Magne's student has problems with the latter when trying to build BeamSIM on Windows10, whereas it is no difference on Ubuntu, seemingly. So the question is, what is consistent to use for any platform?
Please verify this one and I will deal with the other apps later.
> Fixed: Should be "\\" as continuation marker, right?

- SIMElasticity.C
pgc doesn't seem to prune symbols as early in the process as gcc/clang does.
Downstream of https://github.com/OPM/IFEM/pull/151
> add some dummy symbols

- Elasticity.C
- ElasticityUtils.h
- Linear/KirchhoffLovePlate.C
- Linear/Test/Biharmonic1D-p3.reg
- Linear/Test/Biharmonic1D-p3.xinp
- Linear/Test/Harmonic1D-p3.reg
- Linear/Test/Harmonic1D-p3.xinp
- Linear/Test/LR/exact_p2.reg
- Linear/Test/LR/exact_p2.xinp
- Linear/Test/exact_p1.reg
- Linear/Test/exact_p1.xinp
- Linear/Test/exact_p2.reg
- Linear/main_LinEl.C
This essentially fixes two small things:
* Wrong name on the third norm when no analytical solution (was a(e,e)^0.5,e=u-u^r should be (u^r,u^r)
* Avoid printing non-existing residual error in the norm summary for Elasticity (so far exisiting for KL only). Done by inserting integration of area for KirchhoffLove, equivalent to volume for Elasticity.
Also added a linear regression test with non-zero errors.
> Norm name fixes

- Linear/doc/Doxyfile.in
easier to inspect than terminal output, and aids jenkins
https://github.com/OPM/IFEM/pull/252
> changed: redirect doxygen warnings to a log file

- Beam/ElasticBeam.C
- ElasticityUtils.h
- Linear/SIMLinEl.h
- Linear/SIMLinEl2D.C
- Linear/SIMLinEl3D.C
- Linear/SIMLinElBeamC1.C
- Linear/main_LinEl.C
- SIMElasticity.C
- SIMElasticity.h
They are now places in the namespace Elastic instead, mostly because SIMElasticy is a template class such that we (according to Clang) needed one instance of these variables for each template instantiation even though they were relevant for 2D only.
This is an alternative to #54. It has a somewhat larger footprint but we get rid of the dummy 3D variables.
Yet another alternative could be to place them directly in Elasticity scope.
> Changed: Moved some public static variables in SIMElasticity scope

- Linear/CMakeLists.txt
Downstream of https://github.com/OPM/IFEM/pull/309
> fixed: disable test if HDF5 is not enabled

- Beam/ElasticBar.C
- Beam/ElasticBar.h
- Beam/ElasticCable.C
- Beam/ElasticCable.h
- Beam/SIMElasticBar.C
- Linear/Test/Cantilever-Cable3p.reg
- Linear/Test/Cantilever-Cable3p.xinp
- Linear/Test/SS45-Cable4p.reg
- Linear/Test/SS45-Cable4p.xinp
- Linear/Test/SScablePointLoad.reg
- Linear/Test/SScablePointLoad.xinp
If the g2-file is 2D, nsd is reset to 2 and we need only 2 DOFs per node.
Requires OPM/IFEM#326
> Account for pure 2D geometry for cable and bar problems

- Beam/SIMElasticBar.C
- Beam/SIMElasticBar.h
They used to be in SIM1D, but are removed there in OPM/IFEM#335
> Moved some beam-specific attributes and associated methods to SIMElasticBar

- Beam/ElasticBar.C
- Beam/ElasticCable.C
- Beam/ElasticCable.h
- Beam/SIMElasticBar.C
- Beam/SIMElasticBar.h
- Linear/Test/Cantilever-Cable3p.reg
- Linear/Test/SS45-Cable4p.reg
- Linear/Test/SScablePointLoad.reg
On kmm's request. The load is implemented as two opposite-directed transverse loads in the two outer-most control points, and with associated load-correction stiffness in nonlinear simulations. Not fully verified yet. It converges, but very slow..
The other commit here is some changes (also on kmm's request) on the interpretation of material data for cables, mostly for avoiding confusion later on. Now you can use the attribute rhoA to specify the mass per length quantity.
> Support for moment load on C1 cable elements

- Linear/Test/CanTS2D-p1.reg
- Linear/Test/CanTS2D-p2.reg
- Linear/Test/LR/disc-stair-adap.xinp
- Linear/Test/stretch-p1.reg
- Linear/main_LinEl.C
- SIMElasticity.h
The traditional way to calculate sectional forces, only at patch boundaries through.
For comparison with the VCP-calculated ones.
> Added: Surface/edge integration of boundary tractions

- KirchhoffLove.C
- KirchhoffLove.h
- Linear/KirchhoffLovePlate.C
- Linear/KirchhoffLovePlate.h
- Linear/Test/Cantilever-KLplate.reg
- Linear/Test/Cantilever-KLplate.xinp
- Linear/Test/Cantilever-KLshell.reg
- Linear/Test/Cantilever-KLshell.xinp
- Linear/Test/PlateLineLoad.reg
- Linear/Test/PlateLineLoad.xinp
- Linear/Test/PointLoadedPlate-project-file.reg
- Linear/Test/PointLoadedPlate-project-file.xinp
- Shell/SIMKLShell.C
- Shell/SIMKLShell.h
This adds the functionality of specifying a line load in the interior of the domain of a KL-plate problem.
It is restricted to follow the element interfaces (horizontal or vertical), and only one load per patch.
It uses the element interface integrand framework, and requires OPM/IFEM#300 containing some extension/bugfixes of that.
The current implementation is still a bit hackish, but seems to work at least. The parameters defining the location of the line load is currently hard-coded. This needs to be specified via the input file, later.
> Line load for Kirchhoff-Love plate problems

- Elasticity.C
- Elasticity.h
- Linear/ModalDriver.C
- Linear/ModalDriver.h
- Linear/Test/CanTS2D-p2-qstat.reg
- Linear/main_LinEl.C
- NewmarkDriver.h
* The first commit adds the option to output strains instead of stresses, in result points and VTF.
* The second commit adds the option to perform quasi-static modal simulation.
Requires OPM/IFEM#393.
> Quasi-static modal simulation and strain output

- Elasticity.C
- Elasticity.h
- Linear/SIMLinElKL.C
- Linear/SIMLinElKL.h
- Linear/Test/LR/CanTS2D-p1-VCPs.reg
- Linear/Test/LR/CanTS2D-p1-VCPs.xinp
- Linear/Test/LR/CanTS2D-p1.reg
- Linear/main_LinEl.C
- SIMElasticity.h
- SIMElasticityWrap.h
- Shell/SIMKLShell.h
Downstream of OPM/IFEM#384.
The VCP-related stuff is mostly in the postProcessNorms method, where the integrated quantities are divided by the volume of the extraction function support.
> VCP of point-wise stresses

- Linear/SIMLinEl.h
- Linear/Test/LR/CanTS2D-p1-VCPs.reg
- Linear/main_LinEl.C
This should resolve the failure of the last memcheck jenkins job
> Changed: Use zero tolerance when printing boundary/reaction forces

- Elasticity.C
- Linear/SIMLinEl.h
- Linear/SIMLinEl2D.C
- Linear/SIMLinEl3D.C
- Linear/SIMLinElKL.C
- Linear/SIMLinElKL.h
- SIMElasticity.h
- Shell/SIMKLShell.C
For reduced code duplication. A new virtual method parseAnaSol is now the entry point for parsing the "anasol" tag. This method is Dim-independent (no template specialization). Only dimension-dependent hard-coded analytical solutions remain in the parseDimSpecific methods, which no longer are virtual.
> Changed: Refactor the analytical solution parsing

- Linear/CMakeLists.txt
- Linear/Test/LR/Lshape-adap-p2.hreg
- Linear/main_LinEl.C
This should do it, the projections and norms are now correctly written to HDF5 in both cases, I think.
This was broken after #85 with de543470924c2527a394a4bb87ed94e94d92a2ba, probably as a result of this being a much older commit that had been faulty merged with more recent changes, like d64891a8dc371623972a1a6af5986892e7e4ea25 from #50.
OPM/IFEM#413 is then probably not necessary.
> Fixed: Output to hdf5 for adaptive and non-adaptive simulation

- SIMElasticity.h
Affects output to VTF and HDF5 as well as result point printout, no influence on the calculations themselves.
> Added: strain-tag inside the postprocessing context for strain output

- SIMElasticityWrap.C
- SIMElasticityWrap.h
There's a constructor in SimDynElasticitiy passing fields. Since we now explicitly instance the template, this constructor is instanced for SIMElasticityWrap so we need a param.
> fix constructor for FractureDynamics usage

- LinearElasticity.h
- SIMElasticity.h
Fixes crash when built with clang 15 (wrong overload is called for finalizeElement).
Also fix a warning while at it.
> Fix clang crash

- Elasticity.C
- KirchhoffLove.C
- Linear/AnalyticSolutions.C
this to make sure we do not derive a non-symmetric secondary solution from gradient of the primary.
Downstream of https://github.com/OPM/IFEM/pull/649
> mark NavierPlate as a symmetric solution

- Beam/ElasticBar.C
- Beam/ElasticBeam.C
- Beam/SIMElasticBar.C
- ElasticBase.C
- ElasticBase.h
- Elasticity.C
- Elasticity.h
- Linear/Test/SS45-Cable4p.reg
- SIMElasticity.C
- SIMElasticity.h
- Shell/SIMKLShell.C
- Shell/SIMKLShell.h
- jenkins/build.sh
The parsing of gravity vector is moved from class Elasticity to its parent class ElasticBase. The virtual method SIMElasticity::getIntegrand() then returns an ElasticBase pointer instead of Elasticity pointer.
> Extension of ElasticBase interface class

- Beam/ElasticBar.C
- Beam/ElasticBar.h
- Beam/ElasticBeam.C
- Beam/ElasticBeam.h
- ElasticBase.h
- LinearElasticity.C
- LinearElasticity.h
- NewmarkDriver.h
Such that we can remove it from the doxy without issues.
Also, invoke the `finalizeElement()` method without the `FiniteElement` argument directly in `LinearElasticity::finalizeElement()` instead of going via the wrapper.
> Cosmetics: Anonymization of unused argument

- Beam/BeamProperty.C
- Beam/BeamProperty.h
- Beam/ElasticBeam.C
- Linear/CMakeLists.txt
- Linear/Test/SPR/boatbeam.reg
- Linear/Test/boatbeam.reg
This adds the required transformation of the coefficient matrices for beam elements with eccentric end points (w.r.t. their neutral axes). Also a new method for assigning constant beam properties is added.
Requires OPM/IFEM#694
> Beam eccentricity support

- Linear/KirchhoffLovePlate.C
- NewmarkDriver.h
- NonlinearDriver.C
- NonlinearDriver.h
- Shell/KirchhoffLoveShell.C
Basically, the type of the `projSol` member is changed from `Matrix` to `Vectors`, to be aligned with the sibling driver for quasi-static problems, `NonlinearDriver`. Also using the new `utl::vector::push_back()` methods instead of `insert()`.
Requires OPM/IFEM#738
> Minor NewmarkDriver refactoring

- Beam/ElasticBeam.C
- Linear/Test/Beam+supel.reg
- Linear/Test/SPR/Beam+supel.reg
- Linear/Test/SPR/boatbeam.reg
- Linear/Test/boatbeam.reg
The External force vector due to gravity is now computed my multiplying the element mass matrix with the gravitation acceleration vector for each node. Contributions to the rotational DOFs due to the Hermitian interpolation used in the explicitly defined element matrices will then be accounted for.
> Consistent element load vector due to gravity for beam elements

- Linear/DynamicDriver.C
- Linear/DynamicSim.h
- Linear/ModalDriver.C
- Linear/ModalDriver.h
- Linear/MultiLoadCaseDriver.C
- Linear/MultiLoadCaseSim.h
- Linear/main_LinEl.C
- NewmarkDriver.h
- NonlinearDriver.C
- NonlinearDriver.h
* Command-line options `-mlc` for performing multi-load-case analysis (like for ShellSim).
* Saving element norms to VTF and HDF5-file also when projection is not used.
* Saving secondary variables to HDF5 for linear dynamics simulation.
> Various updates

- Beam/ElasticBeam.C
- Beam/ElasticBeam.h
- ElasticBase.C
- ElasticBase.h
- Elasticity.C
- KirchhoffLove.C
- KirchhoffLove.h
- Linear/Test/CanTS2D-p2-dmp.xinp
- Linear/Test/CanTS2D-p2-dyn.xinp
- Linear/Test/RectPlate-modal.xinp
- Linear/Test/Utkrager-dyn.reg
- Linear/Test/Utkrager.xinp
To avoid the unnecessary assembly of coefficient matrices.
Downstream of OPM/IFEM#764.
> Changed: Use SIM::RHS_ONLY mode also for dynamics problems

- Beam/BeamProperty.C
- Beam/BeamProperty.h
- Linear/Test/Beam+KLcyl-p3.reg
- Linear/Test/Beam+Uprofil-p2.reg
- Linear/Test/Beam+supel.reg
- Linear/Test/BeamFrame.reg
- Linear/Test/NREL_5MW_blade-vibration.reg
- Linear/Test/SPR/Beam+KLcyl-p3.reg
- Linear/Test/SPR/Beam+Uprofil-p2.reg
- Linear/Test/SPR/Beam+supel.reg
- Linear/Test/SPR/BeamFrame.reg
- Linear/Test/SPR/NREL_5MW_blade-vibration.reg
- Linear/Test/SPR/Utkrager.reg
- Linear/Test/SPR/boatbeam.reg
- Linear/Test/Tripod.reg
- Linear/Test/Utkrager-Box.reg
- Linear/Test/Utkrager-Box.xinp
- Linear/Test/Utkrager-Pipe.reg
- Linear/Test/Utkrager-Pipe.xinp
- Linear/Test/Utkrager-dyn.reg
- Linear/Test/Utkrager.reg
- Linear/Test/boatbeam.reg
Fixed: Shear reduction factors for hollow Pipe-sections.
Changed: Print cross section area on separate line before the inertias, and also print rotation angle phi and the eccentricities, if non-zero. Move output stream operator out of class scope since members are public.
> Added: Let BeamProperty::parseBox() also handle hollow Box-sections
